TiposDeAplicacoes/QuizzImplementacoes/QuizzMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuizzMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TiposDeAplicacoes/QuizzImplementacoes/QuizzMVC/Controllers/QuizzMVCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.SessionState;
using Quizz;

namespace QuizzMVC.Controllers
{
    public class QuizzMVCController : Controller
    {
        static string diretorioPerguntas = @"PathJson";
        static bool programaIniciado = false;
        // JogoQuizz gameManager = new JogoQuizz(diretorioPerguntas);
        //static private int numeroPergunta = 0;
        //static private int numerodePerguntas = 0;
        //static private bool acabouPrograma = false;
        // GET: QuizzMVC
    


        public ActionResult Index()
        {
            JogoQuizz gameManager = new JogoQuizz(diretorioPerguntas);
            int numerodePerguntas = gameManager.NumeroDePerguntas();
            int numeroPergunta = 0;
            programaIniciado = true;
            //Session.Add("gameManager", gameManager);
            Session["gameManager"] = gameManager;
            Session["numerodePerguntas"] = numerodePerguntas;
            Session["numeroPergunta"] = numeroPergunta;
            return RedirectToAction("ExibirPergunta");
        }

        public ActionResult ExibirPergunta()
        {
            if (programaIniciado == true)
            {
                int numerodePerguntas = (int)Session["numerodePerguntas"];
                int numeroPergunta = (int)Session["numeroPergunta"];
                if (numeroPergunta < numerodePerguntas)
                {
                    var classe = Session["gameManager"] as JogoQuizz;
                    string pergunta = classe.ExibirPerguntaEAlternativas(numeroPergunta);
                    //string pergunta = gameManager.ExibirPerguntaEAlternativas(numeroPergunta);

                    ViewData["perguntaERespostas"] = pergunta;

                    return View();
                }
                else
                {
                    return RedirectToAction("ExibirResultadoFinal");
                }
            }
            else
            {
                return RedirectToAction("AcessoIndevidoPage");
            }
        }

        [HttpPost]
        public ActionResult ValidarResposta(FormCollection CollectionResposta)
        {
            if (programaIniciado == true)
            {
                int numeroPergunta = (int)Session["numeroPergunta"];
                string alternativaEscolhida = CollectionResposta["alternativa"];
                var classe = Session["gameManager"] as JogoQuizz;
                classe.ValidarRespostaUsuario(alternativaEscolhida, numeroPergunta);
                //gameManager.ValidarRespostaUsuario(alternativaEscolhida, numeroPergunta);

                numeroPergunta++;
                Session["numeroPergunta"] = numeroPergunta;
                return RedirectToAction("ExibirPergunta");
            }
            else
            {
                return RedirectToAction("AcessoIndevidoPage");
            }
        }

        public ActionResult ExibirResultadoFinal()
        {
            
            if (programaIniciado == true)
            {
                int numerodePerguntas = (int)Session["numerodePerguntas"];
                int numeroPergunta = (int)Session["numeroPergunta"];
                if (numeroPergunta < numerodePerguntas)
                {
                    return RedirectToAction("AcessoIndevidoPerguntasNaoRespondidas");
                }
                else
                {
                    var classe = Session["gameManager"] as JogoQuizz;
                    //string resultado = gameManager.ResultadoFinal();
                    string resultado = classe.ResultadoFinal();
                    Session.Abandon();
                    programaIniciado = false;

                    ViewData["resultado"] = resultado;

                    return View();
                }
            }
            else
            {
                return RedirectToAction("AcessoIndevidoPage");
            }

        }

        public ActionResult AcessoIndevidoPage()
        {
            Session.Abandon();
            programaIniciado = false;
            return View();
        }

        public ActionResult AcessoIndevidoPerguntasNaoRespondidas()
        {
            Session.Abandon();
            programaIniciado = false;
            return View();
        }
    }
}

TiposDeAplicacoes/QuizzImplementacoes/QuizzMVC/Views/QuizzMVC/AcessoIndevidoPage.cshtml
@{
    ViewBag.Title = "AcessoIndevidoPage";
}

<h2>Acesso Indevido a pagina, o jogo ainda NÃO FOI iniciado.</h2>

TiposDeAplicacoes/QuizzImplementacoes/QuizzMVC/Views/QuizzMVC/AcessoIndevidoPerguntasNaoRespondidas.cshtml
@{
    ViewBag.Title = "AcessoIndevidoPerguntasNaoRespondidas";
}

    <h2>Acesso Indevido a pagina, há perguntas para serem respondidas ainda. REINICIE o Quizz</h2>

TiposDeAplicacoes/QuizzImplementacoes/QuizzMVC/Views/QuizzMVC/ExibirPergunta.cshtml
@{
    ViewBag.Title = "Pergunta";
}

@{ var pergunta = ViewData["perguntaERespostas"];}
<pre>@pergunta</pre>
<br />

@{Html.BeginForm("ValidarResposta", "QuizzMVC");}

    <input type="radio" id="alta" name="alternativa" value="A" />
    <label for="alta">a)</label>
    <br />
    <input type="radio" id="altb" name="alternativa" value="B" />
    <label for="altb">b)</label>
    <br />
    <input type="radio" id="altc" name="alternativa" value="C" />
    <label for="altc">c)</label>
    <br />
    <input type="radio" id="altd" name="alternativa" value="D" />
    <label for="altd">d)</label>
    <br />
    <input type="radio" id="alte" name="alternativa" value="E" />
    <label for="alte">e)</label>
    <br />
    <br />
    <input type="submit" value="Continuar" />

TiposDeAplicacoes/QuizzImplementacoes/QuizzMVC/Views/QuizzMVC/ExibirResultadoFinal.cshtml
@{
    ViewBag.Title = "ExibirResultadoFinal";
}

@{ var resultadoFinal = ViewData["resultado"];}
<h2>@resultadoFinal</h2>

TiposDeAplicacoes/QuizzImplementacoes/QuizzMVC/Views/QuizzMVC/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

TiposDeAplicacoes/QuizzImplementacoes/QuizzMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Quizz", "Index", "QuizzMVC")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>